## 🧼 Data Cleaning Phase

This notebook prepares the raw meningioma dataset for analysis.

The goal is to turn messy clinical/radiological data into a clean, consistent table that can later be used for:

- exploratory analysis
- statistical testing
- logistic regression
- model validation
- Streamlit calculator deployment

At this stage, the priority is **data trustworthiness**, not modeling.

No prediction model is built here.  
This phase only creates the clean foundation.

In [1]:
from IPython.display import Markdown, display
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


from pathlib import Path

In [2]:
#🟧🟧🟧 load dataset and define the ID col
df = pd.read_excel(
    "data/test_Meningiomas_PSKUS_grants.xlsx",
    index_col="Nr."
    )

df.index.name = "case_id"

df.head(0)

Empty DataFrame
Columns: [Personas kods, Unnamed: 2, Vecums, gadi, Dzimums, 0 - vīrietis
1 - sieviete", Histoloģija, 0 - nav
1 - ir, WHO pakāpe (2021), 1 / 2 / 3, Progesterons, 0 - negatīvs
1 - pozitīvs, Ki-67 (%), skaitlis, %, Smadzeņu parenhīmas invāzija, 0 - nav
1 - ir, Nekroze histoloģiski, 0 - nav
1 - ir, MRI izmeklējuma datums, Puse, 1 - labā
2 - kreisā
3 - viduslīnija, Lokalizācija: skull base / non–skull base, 0 - non-skull base
1 - skull base, Cik meningiomas?, Max diametrs, skaitlis,cm, Tilpums, Pamatmodalitāte analīzei, 0 - MRI
1 - CT
3 - MRI+CT, K/v i/v, 0 - nav
1 - ir, 0 - primārs
1 - recidīvs, Audzēja robeža, 1 = gluda,
2 = neregulāra, Dural tail sign, 0 - nav
1 - ir, Gredzenveida kontrastēšanās (tumor capsular enhancement), 0 - nav
1 - ir, Kontrastēšanās veids, 0 - homogēna
1 - heterogēna, Perifokāla tūska, 0 - nav
1 - ir, Perifokālas tūskas tilpums, cm2, Masas efekts, 0 - nav
1 - ir, Audzēja kalcifikācija, 0 - nav
1 - ir, Cistiskas komponentes, 0 - nav
1 - ir, Audzēja nekroze, 0 - nav
1 - ir, Hemorāģiskas sastāvdaļas, 0 - nav
1 - ir
2 - nav skaidri izvērtējams , Kaule hiperostoze, 0 - nav
1 - ir, Kaula invāzija (cortical destruction), 0 - nav
1 - ir, Tumor Hyperintensity on DWI, 0 - nav
1 - ir, Tumor Hyperintensity on T2, 0 - nav
1 - ir, Tumor Hypointensity on T1, 0 - nav
1 - ir, Sīnuss, 0 - neieaug
1 - ieaug
2 - ieaug un cauraug, Cauraug falx cerebri 0 - nav, 1 - ir, ADC map value]
Index: []

[0 rows x 38 columns]

In [3]:
#🟧🟧🟧 comfort renaming
COLUMN_RENAME_MAP = {
    "Personas kods": "patient_code",
    "Unnamed: 2": "entry_year",

    "Vecums, gadi": "age",
    'Dzimums, 0 - vīrietis\n1 - sieviete"': "sex",
    "Histoloģija, 0 - nav\n1 - ir": "histology_available",
    "WHO pakāpe (2021), 1 / 2 / 3": "who_grade",
    "Progesterons, 0 - negatīvs\n1 - pozitīvs": "progesterone_pos",
    "Ki-67 (%), skaitlis, %": "ki67_pct",

    "Smadzeņu parenhīmas invāzija, 0 - nav\n1 - ir": "brain_invasion",
    "Nekroze histoloģiski, 0 - nav\n1 - ir": "hist_necrosis",

    "MRI izmeklējuma datums": "mri_date",
    "Puse, 1 - labā\n2 - kreisā\n3 - viduslīnija": "side",
    "Lokalizācija: skull base / non–skull base, 0 - non-skull base\n1 - skull base": "skull_base",
    "Cik meningiomas?": "meningioma_count",

    "Max diametrs, skaitlis,cm": "max_diameter_cm",
    "Tilpums": "tumor_volume",
    "Pamatmodalitāte analīzei, 0 - MRI\n1 - CT\n3 - MRI+CT": "base_modality",
    "K/v i/v, 0 - nav\n1 - ir": "iv_contrast",
    "0 - primārs\n1 - recidīvs": "primary_vs_recurrent",

    "Audzēja robeža, 1 = gluda, \n2 = neregulāra": "tumor_margin_reg_vs_nonreg",
    "Dural tail sign, 0 - nav\n1 - ir": "dural_tail",
    "Gredzenveida kontrastēšanās (tumor capsular enhancement), 0 - nav\n1 - ir": "capsular_enhancement",
    "Kontrastēšanās veids, 0 - homogēna\n1 - heterogēna": "heterogeneous_enhancement",

    "Perifokāla tūska, 0 - nav\n1 - ir": "perifocal_edema",
    "Perifokālas tūskas tilpums, cm2": "edema_volume_cm2",
    "Masas efekts, 0 - nav\n1 - ir": "mass_effect",

    "Audzēja kalcifikācija, 0 - nav\n1 - ir": "calcification",
    "Cistiskas komponentes, 0 - nav\n1 - ir": "cystic_component",
    "Audzēja nekroze, 0 - nav\n1 - ir": "necrosis",
    "Hemorāģiskas sastāvdaļas, 0 - nav\n1 - ir\n2 - nav skaidri izvērtējams ": "hemorrhage",

    "Kaule hiperostoze, 0 - nav\n1 - ir": "hyperostosis",
    "Kaula invāzija (cortical destruction), 0 - nav\n1 - ir": "cortical_destruction",

    "Tumor Hyperintensity on DWI, 0 - nav\n1 - ir": "dwi_hyperintensity",
    "Tumor Hyperintensity on T2, 0 - nav\n1 - ir": "t2_hyperintensity",
    "Tumor Hypointensity on T1, 0 - nav\n1 - ir": "t1_hypointensity",

    "Sīnuss, 0 - neieaug\n1 - ieaug\n2 - ieaug un cauraug": "sinus_invasion",
    "Cauraug falx cerebri 0 - nav, 1 - ir": "transfalcine_extension",
    "ADC map value": "adc_value",
}

df = df.rename(columns=COLUMN_RENAME_MAP)

df.columns

Index(['patient_code', 'entry_year', 'age', 'sex', 'histology_available',
       'who_grade', 'progesterone_pos', 'ki67_pct', 'brain_invasion',
       'hist_necrosis', 'mri_date', 'side', 'skull_base', 'meningioma_count',
       'max_diameter_cm', 'tumor_volume', 'base_modality', 'iv_contrast',
       'primary_vs_recurrent', 'tumor_margin_reg_vs_nonreg', 'dural_tail',
       'capsular_enhancement', 'heterogeneous_enhancement', 'perifocal_edema',
       'edema_volume_cm2', 'mass_effect', 'calcification', 'cystic_component',
       'necrosis', 'hemorrhage', 'hyperostosis', 'cortical_destruction',
       'dwi_hyperintensity', 't2_hyperintensity', 't1_hypointensity',
       'sinus_invasion', 'transfalcine_extension', 'adc_value'],
      dtype='str')

In [4]:
#🟧🟧🟧 drop unneeded columns
df = df.drop(columns=["patient_code", "entry_year", "mri_date"])

# check for sure that patient_code is not in df
assert "patient_code" not in df.columns

In [5]:
#🟧🟧🟧 fix numeric being datetime (adc_value)
from datetime import date, datetime

print(df.adc_value.unique())

def fix_numeric_being_datetime(x):
    if isinstance(x, (pd.Timestamp, date, datetime)):
        return float(f"{x.day}.{x.month}")
    return x

df["adc_value_raw"] = df["adc_value"]

df.adc_value = df.adc_value.apply(fix_numeric_being_datetime).pipe(pd.to_numeric, errors="coerce")

print(df.adc_value.unique())

display(df.loc[
    df["adc_value"].isna() & df["adc_value_raw"].notna(),
    ["adc_value_raw", "adc_value"]
].drop_duplicates())
df = df.drop(columns=["adc_value_raw"])

[nan '0.88' '0.94' '0.6' datetime.datetime(2026, 2, 1, 0, 0) '0.93' '0.81'
 '0.92' '0.75' '0.85' '0.72' '0.76' 'NAV ADC' '0.69' '0.67' '0.83' '0.84'
 '0.71' '0.87' '0.91' '0.78' 1.05 1.01 '0.7' 'ADC neredz meningiomu'
 '0.51' '0.54' '0.63' '0.99' '1.18' 1.02 '0.79' '0.96' '0.77' '0.89'
 '0.41' 'nosūtīts' '0.58' '0.68' '0.9' datetime.datetime(2026, 3, 1, 0, 0)
 '0.73' '0.98' '0.74' '1.13' '0.95' '0.82' '0.59' '0.48' '0.86' '0.70'
 '1.0' 'nav adc' datetime.datetime(2026, 7, 1, 0, 0) '0.66' '0.90'
 datetime.datetime(2026, 1, 1, 0, 0) 'nav mri' '1.15' '0.815' '0.838'
 '1.27' '1.00' '0.80' '0.49' '1.16' '0.775' '0.848'
 datetime.datetime(2026, 12, 1, 0, 0) 1.07 1.08 '1.17' '0.638'
 datetime.datetime(2026, 11, 1, 0, 0) '0.65' '0.97' '0.62' '1.38' 'nav'
 '0.60']
[  nan 0.88  0.94  0.6   1.2   0.93  0.81  0.92  0.75  0.85  0.72  0.76
 0.69  0.67  0.83  0.84  0.71  0.87  0.91  0.78  1.05  1.01  0.7   0.51
 0.54  0.63  0.99  1.18  1.02  0.79  0.96  0.77  0.89  0.41  0.58  0.68
 0.9   1.3   0.73  0.98  0.74  1.13  0.95  0.82  0.59  0.48  0.86  1.
 1.7   0.66  1.1   1.15  0.815 0.838 1.27  0.8   0.49  1.16  0.775 0.848
 1.12  1.07  1.08  1.17  0.638 1.11  0.65  0.97  0.62  1.38 ]

                 adc_value_raw  adc_value
case_id
16                     NAV ADC        NaN
30       ADC neredz meningiomu        NaN
47                    nosūtīts        NaN
113                    nav adc        NaN
133                    nav mri        NaN
395                        nav        NaN

In [6]:
#🟧🟧🟧 fix string being datetime (ki67_pct)
from datetime import date, datetime

print(df.ki67_pct.unique())

def fix_string_being_datetime(x):
    if isinstance(x, (pd.Timestamp, date, datetime)):
        return f"{x.day}-{x.month}"
    return x

df["ki67_pct_raw"] = df["ki67_pct"]

date_mask = df["ki67_pct"].apply(lambda x: isinstance(x, (pd.Timestamp, date, datetime)))

df["ki67_pct"] = df["ki67_pct"].apply(fix_string_being_datetime).astype("string")

print(df.ki67_pct.unique())

display(
    df.loc[date_mask, ["ki67_pct_raw", "ki67_pct"]]
)

[nan datetime.datetime(2025, 3, 1, 0, 0)
 datetime.datetime(2025, 5, 1, 0, 0) '25-30'
 datetime.datetime(2025, 2, 1, 0, 0) datetime.datetime(2025, 5, 3, 0, 0)
 datetime.datetime(2025, 4, 2, 0, 0) '10-15'
 datetime.datetime(2025, 5, 2, 0, 0) '15-20'
 datetime.datetime(2025, 7, 4, 0, 0) 2 '30-35'
 datetime.datetime(2025, 3, 2, 0, 0) datetime.datetime(2025, 7, 5, 0, 0)
 '20-25' '35-40' '50-60' 1 datetime.datetime(2025, 8, 5, 0, 0)
 datetime.datetime(2025, 10, 7, 0, 0) datetime.datetime(2026, 5, 1, 0, 0)
 datetime.datetime(2025, 12, 10, 0, 0)
 datetime.datetime(2025, 10, 5, 0, 0) datetime.datetime(2025, 4, 3, 0, 0)
 datetime.datetime(2025, 5, 4, 0, 0) 3 5
 datetime.datetime(2025, 10, 8, 0, 0) 4
 datetime.datetime(2025, 6, 4, 0, 0) 7 datetime.datetime(2025, 8, 6, 0, 0)
 datetime.datetime(2025, 9, 5, 0, 0) 10 '15-18' 8
 datetime.datetime(2025, 7, 3, 0, 0) datetime.datetime(2025, 7, 6, 0, 0)
 datetime.datetime(2025, 6, 2, 0, 0) datetime.datetime(2025, 6, 3, 0, 0)
 '18-20' '15-25' datetime.datetime(2025, 6, 5, 0, 0)
 datetime.datetime(2026, 10, 5, 0, 0)]
<ArrowStringArray>
[   <NA>,   '1-3',   '1-5', '25-30',   '1-2',   '3-5',   '2-4', '10-15',
   '2-5', '15-20',   '4-7',     '2', '30-35',   '2-3',   '5-7', '20-25',
 '35-40', '50-60',     '1',   '5-8',  '7-10', '10-12',  '5-10',   '3-4',
   '4-5',     '3',     '5',  '8-10',     '4',   '4-6',     '7',   '6-8',
   '5-9',    '10', '15-18',     '8',   '3-7',   '6-7',   '2-6',   '3-6',
 '18-20', '15-25',   '5-6']
Length: 43, dtype: string

                ki67_pct_raw ki67_pct
case_id
2        2025-03-01 00:00:00      1-3
3        2025-05-01 00:00:00      1-5
5        2025-02-01 00:00:00      1-2
6        2025-02-01 00:00:00      1-2
8        2025-02-01 00:00:00      1-2
...                      ...      ...
395      2025-05-03 00:00:00      3-5
396      2025-06-05 00:00:00      5-6
397      2025-07-03 00:00:00      3-7
398      2025-03-02 00:00:00      2-3
400      2026-10-05 00:00:00     5-10

[220 rows x 2 columns]

In [7]:
#🟧🟧🟧 fix numeric being datetime (max_diameter_cm)
from datetime import date, datetime

print(df.max_diameter_cm.unique())

def fix_numeric_being_datetime(x):
    if isinstance(x, (pd.Timestamp, date, datetime)):
        return float(f"{x.day}.{x.month}")
    return x

df["max_diameter_cm_raw"] = df["max_diameter_cm"]

df.max_diameter_cm = df.max_diameter_cm.apply(fix_numeric_being_datetime)

cleaned = (
        df.max_diameter_cm
        .astype("string")
        .str.strip()
        .str.replace(",", ".", regex=False).pipe(pd.to_numeric, errors="coerce")
        )

print(df.max_diameter_cm.unique())

display(df.loc[
    df["max_diameter_cm"].isna() & df["max_diameter_cm_raw"].notna(),
    ["max_diameter_cm_raw", "max_diameter_cm"]
].drop_duplicates())
df = df.drop(columns=["max_diameter_cm_raw"])

[nan '4.9' '2.8' '4.7' '3.7' '2.9' '4.4' '2.2' '2.3' '3.4' '1.8' '4.0'
 '6.0' '6.4' '7.8' '5.2' '5.1' '3.9' '2.0' '2.6' '5.8' '1.9' '7.3' '9.2'
 '2.7' '4.3' '4' '1.6' '7.4' '3.2' '4.1' '3.5' '4.36' '4.15' '2.1' '4.82'
 '1.21' '3,30' '2.23' '6.1' '6.27' '4.99' '1.77' '8.4' '3.81' '2.5' '4.66'
 '5.79' '2.91' '7.52' '7.9' '2.57' '5.98' '4.72' '4.5' '4.64' '3.0' '4.2'
 '3.1' '3.8' '2.4' '5.4' '3.6' '1.5' '6.5' '4.8' '1.7' '8.0' '7.5'
 datetime.datetime(2026, 8, 2, 0, 0) '8.9' '2' '5.9' '3' '6.8' '5.7' '6.2'
 '7' '1.4' '5' '3.3' '5.3' '4.6' '1.89' '7.1' '6.3' '6.9' '8.2' '5,1'
 '6.6' '6' '5.6' '4,60' '3,8' '3,1' '4,0' '6,30' '3,3' '6,4' '1,8' '3,2'
 '7,8' '2,4' '7.7' '8']
[nan '4.9' '2.8' '4.7' '3.7' '2.9' '4.4' '2.2' '2.3' '3.4' '1.8' '4.0'
 '6.0' '6.4' '7.8' '5.2' '5.1' '3.9' '2.0' '2.6' '5.8' '1.9' '7.3' '9.2'
 '2.7' '4.3' '4' '1.6' '7.4' '3.2' '4.1' '3.5' '4.36' '4.15' '2.1' '4.82'
 '1.21' '3,30' '2.23' '6.1' '6.27' '4.99' '1.77' '8.4' '3.81' '2.5' '4.66'
 '5.79' '2.91' '7.52' '7.9' '2.57' '5.98' '4.72' '4.5' '4.64' '3.0' '4.2'
 '3.1' '3.8' '2.4' '5.4' '3.6' '1.5' '6.5' '4.8' '1.7' '8.0' '7.5' 2.8
 '8.9' '2' '5.9' '3' '6.8' '5.7' '6.2' '7' '1.4' '5' '3.3' '5.3' '4.6'
 '1.89' '7.1' '6.3' '6.9' '8.2' '5,1' '6.6' '6' '5.6' '4,60' '3,8' '3,1'
 '4,0' '6,30' '3,3' '6,4' '1,8' '3,2' '7,8' '2,4' '7.7' '8']

Empty DataFrame
Columns: [max_diameter_cm_raw, max_diameter_cm]
Index: []

In [8]:
display(df.head(2))
print(df.columns)

,age,sex,histology_available,who_grade,progesterone_pos,ki67_pct,brain_invasion,hist_necrosis,side,skull_base,...,hemorrhage,hyperostosis,cortical_destruction,dwi_hyperintensity,t2_hyperintensity,t1_hypointensity,sinus_invasion,transfalcine_extension,adc_value,ki67_pct_raw
case_id,,,,,,,,,,,,,,,,,,,,,
1,67.0,1.0,0.0,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,67.0,1.0,1.0,1,1.0,1-3,0.0,0.0,1.0,1.0,...,0.0,0.0,0.0,1.0,1.0,1.0,0.0,NaN,0.88,2025-03-01 00:00:00

Index(['age', 'sex', 'histology_available', 'who_grade', 'progesterone_pos',
       'ki67_pct', 'brain_invasion', 'hist_necrosis', 'side', 'skull_base',
       'meningioma_count', 'max_diameter_cm', 'tumor_volume', 'base_modality',
       'iv_contrast', 'primary_vs_recurrent', 'tumor_margin_reg_vs_nonreg',
       'dural_tail', 'capsular_enhancement', 'heterogeneous_enhancement',
       'perifocal_edema', 'edema_volume_cm2', 'mass_effect', 'calcification',
       'cystic_component', 'necrosis', 'hemorrhage', 'hyperostosis',
       'cortical_destruction', 'dwi_hyperintensity', 't2_hyperintensity',
       't1_hypointensity', 'sinus_invasion', 'transfalcine_extension',
       'adc_value', 'ki67_pct_raw'],
      dtype='str')

In [9]:
#🟧🟧🟧 convert cols to numeric dtype
really_numeric = ["who_grade", "max_diameter_cm", "tumor_volume"]
for col in really_numeric:
    raw_col = f"{col}_raw"
    df[raw_col] = df[col]
    print(f"{raw_col} - {df[raw_col].dtype} - {df[raw_col].isna().sum()}")
    
    cleaned = (
        df[col]
        .astype("string")
        .str.strip()
        .str.replace(",", ".", regex=False)
    )

    df[col] = pd.to_numeric(cleaned, errors="coerce")

    display(
        df.loc[df[col].isna() & df[raw_col].notna(), [raw_col, col]]
        .drop_duplicates()
        )
    print(f"{col} - {df[col].dtype} - {df[col].isna().sum()}")

who_grade_raw - object - 20

                              who_grade_raw  who_grade
case_id
81                               inoperabls       <NA>
157                       multiplas, exitus       <NA>
158                                  exitus       <NA>
191      gigantiska, no op.atteicās, exitus       <NA>
203                         atteicās no op.       <NA>
266       1x operēta Vācijā, tgd inoperabls       <NA>

who_grade - Int64 - 32
max_diameter_cm_raw - object - 161

Empty DataFrame
Columns: [max_diameter_cm_raw, max_diameter_cm]
Index: []

max_diameter_cm - Float64 - 161
tumor_volume_raw - str - 101

        tumor_volume_raw  tumor_volume
case_id
130             nosutits          <NA>

tumor_volume - Float64 - 103

In [ ]:
col_of_interest = "primary_vs_recurrent"
display(df[col_of_interest].value_counts())
print(df[col_of_interest].isna().sum())

primary_vs_recurrent
0            186
1             21
2              1
multiplas      1
Name: count, dtype: int64

189

### **NESKAIDRIE MOMENTI**
- histology_available = 2.0 .......53....... (jo 0=nav, 1=ir)
- progesterone_pos = 2.0 .......53....... (jo 0=nav, 1=ir)
- skull_base = 2.0 ......291....... (jo 0=non-skull-base, 1=skull-base)
- primary_vs_recurrent = 2 .....111...... (jo 0=primars, 1=recidivs)
- primary_vs_recurrent = multiplas .....157...... (jo 0=primars, 1=recidivs)